### PR TITLE
Possibility to disable gzipping user-data

### PR DESCRIPTION
**Pull request by stffabi**
Some operating systems, e.g. RancherOs rancher/os#2391 don't support gzipped
cloud-init data.
Furthermore always base64 encode user-data, so no special escaping
is needed because the user-data is embedded into the api json request.

### CODE REVIEW

**Comment by greut** [comment]
That's a bummer. It feels heavy to have this into each _compute_. What do you think of putting this into the _provider_ directly?

```hcl
provider "exoscale" {
  gzip = false
}
```

https://www.terraform.io/docs/providers/template/d/cloudinit_config.html

**Comment by stffabi** [comment]
I also thought about putting it onto the provider, but I had in mind this would make it impossible to have mixed compute instances some with gzip active some not.
But I just learned about provider aliases :). Therefore I think that would be a good way to go. I‘m going to adjust the PR and will let you know.

**Comment by greut** [comment]
I'll test that tomorrow morning... thanks a lot!

**Comment by greut** [comment]
@stffabi the base64 only was doable using the [template_cloudinit_config](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html) with `base64=true` and `gzip=false`. We recommend to have both of them set to `false`.

Let's hope RancherOS adds support for gzip soon. Many thanks for your much appreciated contribution!

**Comment by stffabi** [comment]
@greut thanks for including the PR.

Yeah, maybe I have some time to contribute a PR for RancherOS

**Comment by greut** [comment]
Great, hopefully we will be able to provide a proper RancherOS template in the next weeks.

**Pull request merged**
