### PR TITLE
feat(exoscale_sks_cluster): allow upgrades of SKS cluster

### LINKED ISSUE #152: [exoscale_sks_cluster] support kube version upgrades
I have an Exoscale SKS cluster deployed with version `1.22.6`
``` hcl
resource "exoscale_sks_cluster" "sks-cluster" {
...
  version       =  "1.22.6"
}
```

Now I want to upgrade to a new version: 
``` hcl
resource "exoscale_sks_cluster" "sks-cluster" {
...
  version       =  "1.23.3"
}
```

## Current behaviour 
The provider detects correctly that an update is necessary, 
```
  # module.tools.exoscale_sks_cluster.sks-cluster will be updated in-place
  ~ resource "exoscale_sks_cluster" "sks-cluster" {
      ~ version        = "1.22.6" -> "1.23.3"
        # (12 unchanged attributes hidden)
    }

  # module.worker["1"].exoscale_sks_cluster.sks-cluster will be updated in-place
  ~ resource "exoscale_sks_cluster" "sks-cluster" {
      ~ version        = "1.22.6" -> "1.23.3"
        # (12 unchanged attributes hidden)
    }
```
but the version upgrade is not supported and therefore is displayed even after an apply. https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/sks_cluster#version

## Expected behavior
The provider executes an upgrade to the new version. 

## Implementation ideas
Egoscale supports upgrades of an sks cluster. https://github.com/exoscale/egoscale/blob/master/v2/sks_cluster.go#L452

Add an upgrade call, if version has changed to this section: https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/resource_exoscale_sks_cluster.go#L392

### PR DESCRIPTION
**Pull request by secustor**
Closes #152 

Currently not tested therefore only as draft

### CODE REVIEW

**Comment by PhilippeChepy** [comment]
Hello @secustor, thank you for the contribution!
If the acceptance test passes, you can mark your PR as ready for review ;)

A possible improvement is instead of hardcoding Kubernetes versions, query them.

**Comment by secustor** [comment]
I couldn't run the acceptance test as the Makefile includes ( `go.mk/init.mk` & `go.mk/public.mk` ) are pointing to non existing files

**Comment by PhilippeChepy** [comment]
It's a git submodule: `git submodule update --init --recursive go.mk`

**Comment by tstrohmeier** [comment]
+1 for notifications

**Comment by tstrohmeier** [comment]
What is the status of this PR @secustor?

**Comment by secustor** [comment]
It should technically working, but I haven't tested it.

The PR is abandoned as I'm no longer using Exoscale.

**Comment by tstrohmeier** [comment]
@secustor Ok I see. Thank you for your quick answer.

@PhilippeChepy Any chance that we get this PR tested and merged soon?

**Comment by kobajagi** [comment]
I've rebased the code & added tests.

```
$ TF_ACC=1 go test ./... -timeout 60m -run 'TestAccResourceSKSCluster$' -v 
?       github.com/exoscale/terraform-provider-exoscale [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/config      [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/general     [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/list        [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/provider    [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/provider/config     [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/resources/zones     [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/testutils   [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/utils       [no test files]
?       github.com/exoscale/terraform-provider-exoscale/pkg/version     [no test files]
?       github.com/exoscale/terraform-provider-exoscale/version [no test files]
=== RUN   TestAccResourceSKSCluster
    resource_exoscale_sks_cluster_test.go:249: waiting for cluster to be Running, current state: updating
    resource_exoscale_sks_cluster_test.go:249: waiting for cluster to be Running, current state: updating
    resource_exoscale_sks_cluster_test.go:249: waiting for cluster to be Running, current state: updating
    resource_exoscale_sks_cluster_test.go:249: waiting for cluster to be Running, current state: updating
    resource_exoscale_sks_cluster_test.go:249: waiting for cluster to be Running, current state: updating
--- PASS: TestAccResourceSKSCluster (270.31s)
PASS
ok      github.com/exoscale/terraform-provider-exoscale/exoscale        270.316s
testing: warning: no tests to run
PASS
ok      github.com/exoscale/terraform-provider-exoscale/pkg/filter      0.002s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/exoscale/terraform-provider-exoscale/pkg/resources/anti_affinity_group       0.004s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/exoscale/terraform-provider-exoscale/pkg/resources/instance  0.005s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/exoscale/terraform-provider-exoscale/pkg/resources/instance_pool     0.005s [no tests to run]
```

**Review by PhilippeChepy — APPROVED** [review]

**Review by sauterp — APPROVED** [review]

**Pull request merged**
