### PR TITLE
in-place user-data update

### PR DESCRIPTION
**Pull request by stffabi**

### CODE REVIEW

**Comment by stffabi** [comment]
Thanks for your reply. Doesn't that depend on the operating-system used? For example RancherOS retrieves the user-data during every boot and applies it. I also just checked it on your infrastructure with CoreOS, it also applies the user-data during every boot.

The use-case would be e.g. to add an elastic ip after the VM has been created and apply the needed changes to the OS.

**Comment by greut** [comment]
Fair enough, I'll do some checks and revert this artifical limitation.

**Comment by stffabi** [comment]
@greut thanks for merging.

**Comment by greut** [comment]
We thank you, have a great day!

**Pull request merged**
