### PR TITLE
Fix IAM access-key resources

### PR DESCRIPTION
**Pull request by PhilippeChepy**

### CODE REVIEW

**Comment by PhilippeChepy** [comment]
Updated acceptance test passes:

```bash
TF_ACC=true go test -timeout 600s -run ^TestAccResourceIAMAccessKey$ github.com/exoscale/terraform-provider-exoscale/exoscale
# [output]
# ok  	github.com/exoscale/terraform-provider-exoscale/exoscale	5.397s
```

**Review by kobajagi — APPROVED** [review]

**Comment by loomsen-intension** [comment]
Any plans when this is going to be released? :) I really need it.

**Comment by PhilippeChepy** [comment]
Hello @loomsen-intension,

We are planning to release the provider very soon, this week.

**Comment by loomsen-intension** [comment]
Hi @PhilippeChepy,

That's great, thank you very much.

**Pull request merged**
