### PR TITLE
Add ip

### PR DESCRIPTION
**Pull request by greut**
Most of the work is to rewrite the various calls to use the fact that most of the requests are asynchronous.

No IP for the moment.. but it's coming :-)

```hcl
resource "exoscale_elasticip" "public-ip" {
  zone = "${var.zone}"
}
```

### CODE REVIEW

**Comment by greut** [comment]
this works ;-)

```hcl
resource "exoscale_elasticip" "public_ip" {
  zone = "${var.zone}"
}

resource "exoscale_compute" "lb" {
  name = "test-lb"
  template = "${var.template}"
  zone = "${var.zone}"
  size = "Tiny"
  disk_size = 10
}

resource "exoscale_elasticip_associate" "lb_eip" {
  compute_id = "${exoscale_compute.lb.id}"
  elasticip = "${exoscale_elasticip.public_ip.ip}"
}
```

**Comment by greut** [comment]
screenshot from 2017-12-13 13-25-32

```hcl
provider "exoscale" {
  token = "${var.token}"
  secret = "${var.secret}"
}

resource "exoscale_elasticip" "public_ip" {
  zone = "${var.zone}"
}

resource "exoscale_compute" "lb" {
  count = 2
  name = "test-lb-${count.index}"
  template = "${var.template}"
  zone = "${var.zone}"
  size = "Tiny"
  disk_size = 10
  keypair = "${var.keypair}"
}

resource "exoscale_elasticip_associate" "lb_eip" {
  count = "${exoscale_compute.lb.count}"
  compute_id = "${exoscale_compute.lb.*.id[count.index]}"
  elasticip = "${exoscale_elasticip.public_ip.ip}"
}
```

**Comment by greut** [comment]
Installing Docker CE, the quick'n'dirty way.

```hcl
resource "exoscale_compute" "app" {
  name = "test-app"
  template = "${var.template}"
  zone = "${var.zone}"
  size = "Tiny"
  disk_size = 10

  keypair = "${var.keypair}"
  provisioner "remote-exec" {
    connection {
      user = "ubuntu"
      private_key = "${file(var.private_key)}"
      timeout = "15m"
    }
    inline = [
      "sudo apt-get update",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get -qy dist-upgrade",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get -y install apt-transport-https ca-certificates curl software-properties-common",
      "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -",
      // On Artful only Edge is available (use Zesty for CE)
      "sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge\"",
      "sudo apt-get update",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce",
      "sudo systemctl enable docker",
    ]
  }
}
```

**Comment by greut** [comment]
```hcl
resource "exoscale_compute" "app" {
  name = "test-app"
  template = "${var.template}"
  zone = "${var.zone}"
  size = "Tiny"
  disk_size = 12
} 
```

```
$ terraform refresh
$ terraform show
exoscale_compute.app:
  id = 37a6fbff-e909-4ce6-a398-51fc7fc788da
  disk_size = 12
```

**Comment by greut** [comment]
requires https://github.com/exoscale/egoscale/pull/22

**Comment by greut** [comment]
Using _Cloud Init_, to set up Docker and exoip on a machine.

screenshot from 2017-12-19 15-42-41

```yaml
#cloud-config

apt_sources:
- source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful edge"
  key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
    lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
    38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
    L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
    UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
    cmhh4HgeQscQHYgOJjjDVfoY5MucvglbIgCqfzAHW9jxmRL4qbMZj+b1XoePEtht
    ku4bIQN1X5P07fNWzlgaRL5Z4POXDDZTlIQ/El58j9kp4bnWRCJW0lya+f8ocodo
    vZZ+Doi+fy4D5ZGrL4XEcIQP/Lv5uFyf+kQtl/94VFYVJOleAv8W92KdgDkhTcTD
    G7c0tIkVEKNUq48b3aQ64NOZQW7fVjfoKwEZdOqPE72Pa45jrZzvUFxSpdiNk2tZ
    XYukHjlxxEgBdC/J3cMMNRE1F4NCA3ApfV1Y7/hTeOnmDuDYwr9/obA8t016Yljj
    q5rdkywPf4JF8mXUW5eCN1vAFHxeg9ZWemhBtQmGxXnw9M+z6hWwc6ahmwARAQAB
    tCtEb2NrZXIgUmVsZWFzZSAoQ0UgZGViKSA8ZG9ja2VyQGRvY2tlci5jb20+iQI3
    BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEI2BgDwO
    v82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmqvMqd
    tI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3Lgk
    jonyUf9bwtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m
    6fqcd5Fu7pxsqm0EUDK5NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9P
    XRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8OYBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMc
    FYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4DQJjbxeMZbiNMG5kGECA8
    g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSFbzwKB0Jm
    ebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh
    9svIGfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5
    G34Ct5RS7Jt6LIfFdtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoW
    FPIZ7d6vH+Vro6xuWEGiuMaiznap2KhZmpkgfupyFmplh0s6knymuQINBFit2ioB
    EADneL9S9m4vhU3blaRjVUUyJ7b/qTjcSylvCH5XUE6R2k+ckEZjfAMZPLpO+/tF
    M2JIJMD4SifKuS3xck9KtZGCufGmcwiLQRzeHF7vJUKrLD5RTkNi23ydvWZgPjtx
    Q+DTT1Zcn7BrQFY6FgnRoUVIxwtdw1bMY/89rsFgS5wwuMESd3Q2RYgb7EOFOpnu
    w6da7WakWf4IhnF5nsNYGDVaIHzpiqCl+uTbf1epCjrOlIzkZ3Z3Yk5CM/TiFzPk
    z2lLz89cpD8U+NtCsfagWWfjd2U3jDapgH+7nQnCEWpROtzaKHG6lA3pXdix5zG8
    eRc6/0IbUSWvfjKxLLPfNeCS2pCL3IeEI5nothEEYdQH6szpLog79xB9dVnJyKJb
    VfxXnseoYqVrRz2VVbUI5Blwm6B40E3eGVfUQWiux54DspyVMMk41Mx7QJ3iynIa
    1N4ZAqVMAEruyXTRTxc9XW0tYhDMA/1GYvz0EmFpm8LzTHA6sFVtPm/ZlNCX6P1X
    zJwrv7DSQKD6GGlBQUX+OeEJ8tTkkf8QTJSPUdh8P8YxDFS5EOGAvhhpMBYD42kQ
    pqXjEC+XcycTvGI7impgv9PDY1RCC1zkBjKPa120rNhv/hkVk/YhuGoajoHyy4h7
    ZQopdcMtpN2dgmhEegny9JCSwxfQmQ0zK0g7m6SHiKMwjwARAQABiQQ+BBgBCAAJ
    BQJYrdoqAhsCAikJEI2BgDwOv82IwV0gBBkBCAAGBQJYrdoqAAoJEH6gqcPyc/zY
    1WAP/2wJ+R0gE6qsce3rjaIz58PJmc8goKrir5hnElWhPgbq7cYIsW5qiFyLhkdp
    YcMmhD9mRiPpQn6Ya2w3e3B8zfIVKipbMBnke/ytZ9M7qHmDCcjoiSmwEXN3wKYI
    mD9VHONsl/CG1rU9Isw1jtB5g1YxuBA7M/m36XN6x2u+NtNMDB9P56yc4gfsZVES
    KA9v+yY2/l45L8d/WUkUi0YXomn6hyBGI7JrBLq0CX37GEYP6O9rrKipfz73XfO7
    JIGzOKZlljb/D9RX/g7nRbCn+3EtH7xnk+TK/50euEKw8SMUg147sJTcpQmv6UzZ
    cM4JgL0HbHVCojV4C/plELwMddALOFeYQzTif6sMRPf+3DSj8frbInjChC3yOLy0
    6br92KFom17EIj2CAcoeq7UPhi2oouYBwPxh5ytdehJkoo+sN7RIWua6P2WSmon5
    U888cSylXC0+ADFdgLX9K2zrDVYUG1vo8CX0vzxFBaHwN6Px26fhIT1/hYUHQR1z
    VfNDcyQmXqkOnZvvoMfz/Q0s9BhFJ/zU6AgQbIZE/hm1spsfgvtsD1frZfygXJ9f
    irP+MSAI80xHSf91qSRZOj4Pl3ZJNbq4yYxv0b1pkMqeGdjdCYhLU+LZ4wbQmpCk
    SVe2prlLureigXtmZfkqevRz7FrIZiu9ky8wnCAPwC7/zmS18rgP/17bOtL4/iIz
    QhxAAoAMWVrGyJivSkjhSGx1uCojsWfsTAm11P7jsruIL61ZzMUVE2aM3Pmj5G+W
    9AcZ58Em+1WsVnAXdUR//bMmhyr8wL/G1YO1V3JEJTRdxsSxdYa4deGBBY/Adpsw
    24jxhOJR+lsJpqIUeb999+R8euDhRHG9eFO7DRu6weatUJ6suupoDTRWtr/4yGqe
    dKxV3qQhNLSnaAzqW/1nA3iUB4k7kCaKZxhdhDbClf9P37qaRW467BLCVO/coL3y
    Vm50dwdrNtKpMBh3ZpbB1uJvgi9mXtyBOMJ3v8RZeDzFiG8HdCtg9RvIt/AIFoHR
    H3S+U79NT6i0KPzLImDfs8T7RlpyuMc4Ufs8ggyg9v3Ae6cN3eQyxcK3w0cbBwsh
    /nQNfsA6uu+9H7NhbehBMhYnpNZyrHzCmzyXkauwRAqoCbGCNykTRwsur9gS41TQ
    M8ssD1jFheOJf3hODnkKU+HKjvMROl1DK7zdmLdNzA1cvtZH/nCC9KPj1z8QC47S
    xx+dTZSx4ONAhwbS/LN3PoKtn8LPjY9NP9uDWI+TWYquS2U+KHDrBDlsgozDbs/O
    jCxcpDzNmXpWQHEtHU7649OXHP7UeNST1mCUCH5qdank0V1iejF6/CfTFU4MfcrG
    YT90qFF93M3v01BbxP+EIY2/9tiIPbrd
    =0YYh
    -----END PGP PUBLIC KEY BLOCK-----


package_update: true
package_upgrade: true

packages:
- docker-ce
- ifupdown
- jq

write_files:
- path: /etc/network/interfaces
  content: |
    source /etc/network/interfaces.d/*.cfg
- path: /etc/network/interfaces.d/51-exoip.cfg
  content: |
    auto lo:1
    iface lo:1 inet static
      address ${elasticip}
      netmask 255.255.255.255
      exoscale-peer-group ${peer_group}
      exoscale-api-key ${token}
      exoscale-api-secret ${secret}
      exoscale-api-endpoint ${endpoint}
      up /usr/local/bin/exoip -W &

runcmd:
- [ sh, -c, "wget https://github.com/exoscale/exoip/releases/download/0.3.2/exoip" ]
- [ sh, -c, "wget https://github.com/exoscale/exoip/releases/download/0.3.2/exoip.asc" ]
- [ sh, -c, "gpg --recv-keys E458F9F85608DF5A22ECCD158B58C61D4FFE0C86" ]
- [ sh, -c, "gpg --verify --trust-model always exoip.asc && sudo chmod +x exoip && sudo mv exoip /usr/local/bin/" ]
- [ sh, -c, "sudo ifup lo:1" ]

```

```hcl
resource "exoscale_securitygroup" "docker" {
  name = "docker-swarm"

  ingress_rules = {
    protocol = "TCP"
    port = 2377
    // We've got a cycle in the dag, here...
    //user_security_group_list = ["${exoscale_securitygroup.docker.id}"]
    //user_security_group_list = ["docker-swarm"]
    cidr = "0.0.0.0/0"
  }
}

resource "exoscale_elasticip" "public_ip" {
  zone = "${var.zone}"
}

data "template_file" "script" {
  template = "${file("init.tpl")}"

  vars {
    elasticip = "${exoscale_elasticip.public_ip.ip}"
    peer_group = "${exoscale_securitygroup.docker.name}"
    token = "${var.token}"
    secret = "${var.secret}"
    endpoint = "${var.endpoint}"
  }
}

resource "exoscale_compute" "docker" {
  name = "test-app"
  template = "${var.template}"
  zone = "${var.zone}"
  size = "Tiny"
  disk_size = 13  // for good luck

  keypair = "${var.keypair}"
  securitygroups = ["default", "docker-swarm"]

  user_data = "${data.template_file.script.rendered}"
}
```

**Comment by greut** [comment]
@pyr do you mind if I merge this into _dev_?

**Comment by oresot** [comment]
So, how does this work? Can we associate Elastic IPs to compute instances using terraform?

I can't find any reference in the code to [exoscale_elasticip_associate](https://github.com/exoscale/terraform-provider-exoscale/pull/33#issuecomment-351377482), but there are calls to the API AddIPToNic

Thanks!

**Comment by greut** [comment]
@oresot It got renamed to [`exoscale_ipaddress`](https://github.com/exoscale/terraform-provider-exoscale#elastic-ip-address) to match the CloudStack provider. Using Terraform, you'll associate the EIP on the Cloudstack side of the story. You'll still need to configure the interface using `cloud-init`.

```yaml
#cloud-config
package_update: true
package_upgrade: true

packages:
- ifupdown

write_files:
- path: /etc/network/interfaces
  content: |
    source /etc/network/interfaces.d/*.cfg
- path: /etc/network/interfaces.d/51-eip.cfg
  content: |
    auto lo:1
    iface lo:1 inet static
      address ${elasticip}
      netmask 255.255.255.255

runcmd:
- [ sudo, ifup, "lo:1" ]
```

Cheers,

**Pull request merged**
