### PR TITLE
Refactor to support new API

### PR DESCRIPTION
**Pull request by greut**
- [x] new api
- [x] importing, updating, scaling compute
- [x] importing, updating (anti-)affinity groups
- [x] importing, updating ip
- [x] importing, updating ssh keys
- [x] importing, updating security groups
- [x] import, updating DNS
- [x] versioning
- [x] tags (on compute)

Apply https://github.com/exoscale/egoscale/pull/25

### CODE REVIEW

**Comment by greut** [comment]
This let you import/udpate a compute resource (basic changes though)

**Comment by greut** [comment]
```hcl
resource "exoscale_compute" "isaac" {
  name = "isaac"
  state = "Stopped"
}
```

```
Terraform will perform the following actions:                                                                                 
                                                                                                  
  ~ exoscale_compute.isaac                                                                                                    
      state: "Running" => "Stopped" 
```

**Comment by greut** [comment]
`id` and `name` are identical, so it's easy to import it. Although... I don't see any simple way to import a record.

```hcl
resource "exoscale_domain" "exo" {
  name = "exo.exo"
}

resource "exoscale_domain_record" "glop" {
  domain = "${exoscale_domain.exo.id}"
  name = "glap"
  record_type = "CNAME"
  content = "${exoscale_domain.exo.name}"
}
```

**Comment by greut** [comment]
import everything!!

```console
$ terraform import exoscale_security_group.default 21a14a60-be48-4bde-8509-ae6ed0231ed0
$ terraform show
exoscale_security_group.default:
  id = 21a14a60-be48-4bde-8509-ae6ed0231ed0
  description = Default Security Group
  name = default
exoscale_security_group_rule.default:
  id = a3ebbef3-2fbf-4986-ba6a-9a747febbd90
  cidr = 0.0.0.0/0
  end_port = 22
  icmp_code = 0
  icmp_type = 0
  protocol = TCP
  security_group_id = 21a14a60-be48-4bde-8509-ae6ed0231ed0
  security_group_name = default
  start_port = 22
  type = INGRESS
exoscale_security_group_rule.default-1:
  id = 07c53c41-e81f-43c4-aad8-7b5b6c0a9c28
  cidr = 0.0.0.0/0
  end_port = 0
  icmp_code = 0
  icmp_type = 8
  protocol = ICMP
  security_group_id = 21a14a60-be48-4bde-8509-ae6ed0231ed0
  security_group_name = default
  start_port = 0
  type = INGRESS
```

**Comment by greut** [comment]
```
exoscale_domain.exo:
  id = exo.exo
  auto_renew = false
  expires_on =
  name = exo.exo
  state = hosted
exoscale_domain_record.exo:
  id = 13027574
  domain = exo.exo
  name = hello
  prio = 0
  record_type = TXT
  ttl = 3600
```

**Comment by greut** [comment]
```
exoscale_compute.ada:
  tags.% = 2
  tags.a = test
  tags.this = is
```

**Comment by marcaurele** [comment]
I'm not in favor of duplicating the CS logic into the driver itself, and would let CS return the error code. For example I would not do the prevention for affinity groups because there is a way to *unlock* this limitation: e1c127f900b8a2bd19b7f0093ec84c0f8133adf5. Disk shrinkage make sense, so this can be an exception to return a quicker feedback to the user.

**Comment by greut** [comment]
@marcaurele my intentions were that if a command fail, the VM is in a _Stopped_, half-backed state. It's not optimal but preventing any issue is good to do.

**Pull request merged**
