### PR TITLE
secondary ip: create a compound id instead of the cs id

### LINKED ISSUE #125: secondaryip id issue
The `id` of the `secondaryip_resource` is the one from CloudStack, which is difference if you destroy/recreate the relation. It causes trouble when coupled with exoip, which may delete/recreate the association.

https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/secondaryip_resource.go#L173

**proposition** use a compound key containing the VM and the IP address.

/cc @JessicaToscani

### PR DESCRIPTION
**Pull request by greut**
The `secondary_ipaddress` doesn't represents the Cloudstack ID anymore.

Fixes #125 

```diff
 exoscale_secondary_ipaddress.machine:                                                     
-  id = 622ae049-b9a6-47f0-949d-8f180ac778dd
+  id = 3ce82e42-fe7e-4e94-b304-b3656b296d35_159.100.251.202          
   compute_id = fd9117ab-dd6a-4674-93e1-70d272fcb85c                                     
   ip_address = 159.100.251.202                                                                      
   network_id = d48bfccc-c11f-438f-8177-9cf6a40dc4f8
   nic_id = 3ce82e42-fe7e-4e94-b304-b3656b296d35
```

/cc @llambiel

- [ ] create via tf, delete/reattach via portal, apply again

### CODE REVIEW

**Comment by greut** [comment]
@JessicaToscani there is a new example to run and play with this change.

**Comment by greut** [comment]
@LaCap if you could test it, that would be awesome.

**Comment by greut** [comment]
@LaCap how can I help you help me?

**Comment by greut** [comment]
@LaCap this one should work better, thanks!

https://ppsos-ch-dk-2.exo.io/yoanyoanyoan/terraform-provider-exoscale_v0.9.25_xfd0ce94.bz2

**Comment by LaCap** [comment]
@greut apparently not:

```
blah examples/elastic-ip ‹associate-ip-id*› » terraform plan  
var.key_pair
  Enter a value: ...


Warning: provider.exoscale: "profile": [DEPRECATED] Use region instead



Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

exoscale_ipaddress.ingress: Refreshing state... (ID: c2d51905-9157-49ca-abf4-57916199a321)
exoscale_compute.machine: Refreshing state... (ID: f5a43466-524f-462c-a839-18d1ba57fc86)
exoscale_secondary_ipaddress.machine: Refreshing state... (ID: f91d7889-9cb8-48f4-8003-7f67b8a6389a)

Error: Error refreshing state: 1 error(s) occurred:

* exoscale_secondary_ipaddress.machine: 1 error(s) occurred:

* exoscale_secondary_ipaddress.machine: exoscale_secondary_ipaddress.machine: API error ParamError 431 (ServerApiException 9999): Unable to execute API command listnics due to invalid value. Invalid parameter nicid value=e4a57c66-3be8-48fe-a47a-518f9dd5ee20 due to incorrect long value format, or entity does not exist or due to incorrect parameter annotation for the field in api cmd class.
```
Or maybe I'm doing something wrong.

**Comment by greut** [comment]
@LaCap thanks! You may rename the _profile_ into _region_ in `main.tf`.

https://ppsos-ch-dk-2.exo.io/yoanyoanyoan/terraform-provider-exoscale_v0.9.25_xac48aa9.bz2

**Comment by greut** [comment]
@LaCap jamais deux sans trois.

https://ppsos-ch-dk-2.exo.io/yoanyoanyoan/terraform-provider-exoscale_v0.9.25_x179ad5b.bz2

**Comment by LaCap** [comment]
@greut nope...
Still the same error:

```
* exoscale_secondary_ipaddress.machine: exoscale_secondary_ipaddress.machine: API error InternalError 530 (ServerApiException 9999): Virtual machine id does not exist
```

**Comment by greut** [comment]
run the example, destroy the machine, refresh = :boom: ...

**Comment by greut** [comment]
@LaCap yet another one :-)

https://ppsos-ch-dk-2.exo.io/yoanyoanyoan/terraform-provider-exoscale_v0.9.25_x2c50642.bz2

**Comment by LaCap** [comment]
@greut :+1: works better now.

**Comment by greut** [comment]
thanks and sorry for the too many try'n'fail

**Pull request merged**
