### PR TITLE
compute: use Details to activate ipv6

### PR DESCRIPTION
**Pull request by greut**
Signed-off-by: Yoan Blanc <yoan.blanc@exoscale.ch>

### CODE REVIEW

**Comment by marcaurele** [comment]
Not needed to change the way we perform the call since it's pure Exoscale

**Comment by greut** [comment]
I like to have something that uses the `map[string]string` serialization

**Comment by brutasse** [comment]
Apart from the build status, this looks ready -- @greut what do you think?

**Comment by greut** [comment]
there is no rush

**Pull request merged**
