### PR TITLE
User-oriented readme

### PR DESCRIPTION
**Pull request by janoszen**
As a first step of improving the provider, I reformatted the readme to be more geared towards a user rather than a developer. I hope this is ok, please let me know if I need to change anything.

### CODE REVIEW

**Comment by greut** [comment]
See: #135

**Comment by janoszen** [comment]
Hey @greut thank you, I'll integrate the information from that issue into the readme.

**Comment by greut** [comment]
My apologies if I wasn't clear. The README is the one from the terraform-providers organization. Unless they change it there, we won't change it here.

**Comment by janoszen** [comment]
Understood, thank you. Depending on what the timeline for the merge is, would it make sense to at least temporarily add the friendlier readme so people find something helpful when they google?

Alternatively, what can we do to speed the original merge along?

**Comment by pyr** [comment]
Hi @janoszen,

We're now 4th in line so things should move fast for the integration, but there's not much more we can do than wait, thanks again!

**Pull request closed without merging**
